### ISSUE TITLE
Not compatible with ES6

### ISSUE THREAD

**Issue by Hypercubed** [puffnfresh/emu.js#3]
To make emu compatible with ES6 (and perhaps other JS flavors) I replaced esprima with [getify/literalizer](https://github.com/getify/literalizer).  You can see the result in this [dev branch](https://github.com/Hypercubed/emu.js/tree/dev).

If you are interested in this I'll submit a PR, otherwise, I'll create a divergent fork and rename the project, perhaps called `heuristic-sdg`.

**Comment by Hypercubed** [comment]
@puffnfresh I'd like to get your thoughts before proceeding.... whether you would like me to do a PR or create a divergent project.

**Comment by puffnfresh** [comment]
Submit a PR, I'll take a look.

**Comment by Hypercubed** [comment]
Looks great!!!  Perhaps needs a major version bump on publish.

**Comment by Hypercubed** [comment]
Hi @puffnfresh, thanks for adding me as a collaborator.

Do you think you will publish this to npm?

**Comment by Hypercubed** [comment]
@DamonOehlman as a user of emu (are you still?) do you have any issues publishing this change.  I think in general it should make emu more flexible with little impact to users.

**Comment by DamonOehlman** [comment]
@Hypercubed SGTM :)

**Comment by puffnfresh** [comment]
@Hypercubed you've got npm access now

**Comment by Hypercubed** [comment]
Done, published as 1.0.0.  Thanks.

**Comment by Hypercubed** [comment]
Any idea why npm still shows the old version?  https://www.npmjs.com/package/emu

npm-cli installs 1.0.0

**Comment by puffnfresh** [comment]
@Hypercubed that is bizarre, seems like a bug in npm to me!

**Comment by Hypercubed** [comment]
Maybe because I published to a package under your name?  I've never done that before.
